# Generated by Django 3.0.6 on 2020-06-15 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='menu',
            new_name='species',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
